import './style.scss';
import './js/variables';
import './js/submitButton';
import './js/show-button';
import './js/input--name';
import './js/input--email';
import './js/input--password';
import './js/input--password-repeat';
import './js/form';
